language: python
dist: trusty
cache: pip
python:
  - 3.4
  - 3.5
  - 3.6

os:
  - linux

env:
  global:
  - PYTHONUNBUFFERED=yes
  matrix:
  - MATRIX_TOXENV=unit
before_install:
  - if [[ -v MATRIX_TOXENV ]]; then export TOXENV=${TRAVIS_PYTHON_VERSION}-${MATRIX_TOXENV}; fi; env

script:
    - tox -vv
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
